#!/usr/bin/env python3
"""Generate the public CLI inventory from the Typer application.

The generated Markdown is intentionally compact and deterministic.  It records
the public command tree and every declared argument/option without copying
Rich's terminal-oriented help rendering into the documentation.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from typer._click.core import Command
from typer.core import TyperArgument, TyperGroup, TyperOption
from typer.main import get_command

from lorekeep.cli import app


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docs" / "reference" / "cli.md"


def _one_line(value: str | None) -> str:
    if not value:
        return ""
    # Join the first docstring paragraph because summaries can wrap in source.
    # Split before a likely next sentence only when it starts with uppercase;
    # this avoids treating the dot in "e.g. provider.model" as a boundary.
    paragraph = re.split(r"\n\s*\n", value.strip(), maxsplit=1)[0]
    paragraph = re.sub(r"\s+", " ", paragraph).strip()
    summary = re.split(r"(?<=[.!?])\s+(?=[A-Z])", paragraph, maxsplit=1)[0]
    return summary.replace("|", "\\|")


def _parameter_names(command: Command) -> str:
    names: list[str] = []
    for param in command.params:
        if getattr(param, "hidden", False):
            continue
        if isinstance(param, TyperArgument):
            name = param.human_readable_name.upper()
            names.append(f"`<{name}>`" if param.required else f"`[{name}]`")
            continue
        if not isinstance(param, TyperOption):
            continue
        options = [*param.opts, *param.secondary_opts]
        if not options or all(option in {"--help"} for option in options):
            continue
        names.append("`" + " / ".join(options) + "`")
    return "<br>".join(names) if names else "—"


def _walk(group: Command, prefix: tuple[str, ...] = ()):
    for name, command in group.commands.items():
        if command.hidden:
            continue
        path = (*prefix, name)
        yield path, command
        if isinstance(command, TyperGroup):
            yield from _walk(command, path)


def render() -> str:
    root = get_command(app)
    assert isinstance(root, TyperGroup)
    rows = []
    for path, command in _walk(root):
        rows.append(
            "| `lorekeep "
            + " ".join(path)
            + "` | "
            + _one_line(command.help)
            + " | "
            + _parameter_names(command)
            + " |"
        )

    root_options = _parameter_names(root)
    return "\n".join(
        [
            "# CLI reference",
            "",
            "<!-- Generated by scripts/generate_cli_reference.py; do not edit by hand. -->",
            "",
            "This is the public command surface generated from the Typer application.",
            "Hidden compatibility/development commands are intentionally omitted. Run",
            "`lorekeep <command> --help` for types, defaults, and detailed usage.",
            "",
            f"Global options: {root_options}.",
            "",
            "| Command | Purpose | Arguments and options |",
            "|---|---|---|",
            *rows,
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Fail instead of writing when stale."
    )
    args = parser.parse_args()
    expected = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if current != expected:
            print(
                f"{TARGET.relative_to(ROOT)} is stale; run "
                "`uv run python scripts/generate_cli_reference.py`",
                file=sys.stderr,
            )
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
